### ISSUE TITLE
port existing tests to ginkgo, add some missing tests

### ISSUE THREAD

**Issue by MichaHoffmann** [aiven/aiven-go-client#124]
Currently there are some tests using the standard library and some that use ginkgo. It would be nice to use the same testing framework for all tests. One could use that opportunity to extend the existing tests to increase coverage a little.

**Comment by Serpentiel** [comment]
hey, @MichaHoffmann! 👋 

thanks for raising this issue up, but unfortunately, we've decided that we would like to move for the standard library instead, since ginkgo has its drawbacks to it

I'll close this issue for now :)
