### ISSUE TITLE
func to list all KafkaAcl

### ISSUE THREAD

**Issue by jmlero** [aiven/aiven-go-client#201]
The function to list all the Kafka ACL entries uses the Services endpoint. According to the comment:

```
// List lists all the Kafka ACL entries.

func (h *KafkaACLHandler) List(project, serviceName string) ([]*KafkaACL, error) {

	// There's no API for listing Kafka ACL entries. Need to get them from
	// service info instead
    service, err := h.client.Services.Get(project, serviceName)
```

But there is an endpoint to get directly all Kafka Acl: [https://api.aiven.io/doc/#operation/ServiceKafkaAclList](https://api.aiven.io/doc/#operation/ServiceKafkaAclList)

Would make sense to use `ServiceKafkaAclList` instead of `ServiceList`?

**Comment by Serpentiel** [comment]
hey, @jmlero! 👋

thanks for suggesting this, could you please let us know if this is something you still would like to see implemented?

**Comment by Serpentiel** [comment]
Hey, @jmlero! 👋

This should be available in https://github.com/aiven/go-client-codegen.

I will close this issue for now, and would recommend migrating to the code-generated Go client instead.
