### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mortenlj** [aiven/aiven-go-client#209]
We need to manage Kafka Schema Registry ACLs, and I see the code to do that is on master, but there hasn't been a release made since November last year.

Any chance of a new release soon?

**Comment by Serpentiel** [comment]
hey, @mortenlj! 👋

thanks for raising this question up! we've implemented automatic releases in this project, and you should now be able to get updates for our latest features instantly

I'm going to close this issue for now :)
