### ISSUE TITLE
Necessity of account id and team id after token authentication

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [aiven/aiven-go-client#331]
After authenticating with [`NewTokenClient`](https://github.com/aiven/aiven-go-client/blob/a27065a3e3a56e2ec64b6e8cff30fa55cb3fc850/client.go#L138) and getting a new `*client`, why is there a [need](https://github.com/aiven/aiven-go-client/blob/a27065a3e3a56e2ec64b6e8cff30fa55cb3fc850/account_team_projects.go#L29) to pass `accountId` and `teamId` to list the projects? Aren't tokens account/team specific?

Is there a way to retrieve those values (`accountId` / `teamId`) from the `client` instance?

**Comment by Serpentiel** [comment]
Hey, @pantelis-karamolegkos! 👋 

That's a great question, but I would suggest checking if https://github.com/aiven/go-client-codegen works better for your needs.

We will be gradually moving to it, and this project will soon be deprecated, and replaced with the one that I linked.

If you haven't yet started using the client and are simply checking on the things, the new client should be the way to go.

Thank you! Please let me know if you would like to stick to this client for some reason, and I'll happily provide you with assistance 🙂

**Comment by pantelis-karamolegkos** [comment]
@Serpentiel thanks for your kind reply. I am already moving to the new project and created my first [issue](https://github.com/aiven/go-client-codegen/issues/34) (more of a question) in case you have any idea about it.
