### ISSUE TITLE
Is powered field valid for ServiceGet api response?

### ISSUE THREAD

**Issue by ChathurangaKCD** [aiven/aiven-go-client#365]
https://api.aiven.io/doc/#tag/Service/operation/ServiceGet doesn't define a property `powered` in it's response.
But Service type used in ServiceGet response type has such field.
```
type (
	// Service represents the Service model on Aiven.
	Service struct {
	...
	Powered bool `json:"powered"`
```

Looks like this was added in https://github.com/aiven/aiven-go-client/pull/71/files . 
Since the actual response doesn't contain this, value returned from client is always `false` ( the default for `bool` type. )

**Comment by rriski** [comment]
Hey @ChathurangaKCD 👋 Indeed, the `Powered` field is incorrect and isn't part of `ServiceGet` response. I have opened https://github.com/aiven/aiven-go-client/pull/367 that removes the field to avoid confusion.
