### ISSUE TITLE
Getting a Kafka Topic immediately after creation sometimes fails.

### ISSUE THREAD

**Issue by eyeezzi** [aiven/aiven-go-client#59]
I came across this behaviour because I was trying to obtain the Kafka Topic that I had just created. 

## How to reproduce

```go
var int p = 2
var int r = 20000

req := aiven.CreateKafkaTopicRequest{
    TopicName: "test",
    Partitions: &p,
    RetentionBytes: &r,
}

if err := Client.KafkaTopics.Create("project", "service", req); err != nil {
    return err
}

topic, err := Client.KafkaTopics.Get("project", "service", "test")
if err != nil {
    return "Getting created topic failed!"
}

return topic
```

## What I think is going on

The `Client.KafkaTopics.Create(...)` returns an `error` instead of `(KafkaTopic, error)`, so, I have to get the created topic with `Client.KafkaTopics.Get(...)`. The latter method is what fails with a 501 HTTP response, the failure is non-deterministic. 

My hypothesis is that the .Create() method returns success even when **the topic is still being created**, so the topic sometimes doesn't exist by the time the GET method executes.

## What do I expect?

I'd expect the topic to be 'gettable' after CREATE already returned a 200 OK.

**Comment by ivan-savciuc** [comment]
Hello,

Indeed sometimes Aiven Kafka topics are not immediately available after creation, same holds for other entities like Service, Kafka ACL, etc. Aiven API is eventually consistent similarly to all modern Cloud APIs like AWS or GCP. 

When a user creates a Kafka Topic via Aiven API/Client and if a creation request fulfils all requirements like preexisting running Kafka service, Unique Topic name, etc. API responds with OK 20X status code, meaning that provisioning of a Kafka Topic has begun, thought might take some time until newly created Kafka topic will be fully functioning.

And we encourage our Aiven Go Client users to handle such logic on their side. Go Client library provides a simple wrapper on top of Aiven API and exposes all inners states of API objects back to the user without any extra layer in between.  

I do recommend checking this https://github.com/aiven/terraform-provider-aiven/blob/master/aiven/kafka_topic_availability.go#L23 for client-side implementation of Kafka Topic availability use-case. 

Have a great day,
Ivan
